version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"

  # Docker
  - package-ecosystem: "docker"
    directory: "/multi-tenancy-demo"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"

  # NPM
  - package-ecosystem: "npm"
    directory: "/multi-tenancy-demo"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "npm"
    versioning-strategy: increase
