version: "3.8"

services:
  oathkeeper:
    image: oryd/oathkeeper:v0.40.9
    ports:
      - "4455:4455" # proxy (consistent port mapping)
      - "4456:4456" # api
    restart: unless-stopped
    command:
      - serve
      - --config
      - /etc/config/oathkeeper/oathkeeper.yml
    environment:
      - LOG_LEVEL=debug
    volumes:
      - type: bind
        source: ./config
        target: /etc/config/oathkeeper
    networks:
      - ory

networks:
  ory:
    external: true
    name: ory-network
