version: "v0.14.0"

log:
  level: debug

namespaces:
  # Global permissions namespace - defines all possible permissions
  - id: 0
    name: default

serve:
  read:
    host: 0.0.0.0
    port: 4466
  write:
    host: 0.0.0.0
    port: 4467

dsn: postgres://postgres:postgres@postgres:5432/keto?sslmode=disable
