version: "3.8"

services:
  multi-tenancy-demo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: multi-tenancy-demo
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=production
      - PORT=9000
      - KRATOS_PUBLIC_URL=http://kratos:4433
      - KRATOS_ADMIN_URL=http://kratos:4434
      - KETO_READ_URL=http://keto:4466
      - KETO_WRITE_URL=http://keto:4467
    networks:
      - ory
    restart: unless-stopped

networks:
  ory:
    external: true
    name: ory-network
